In [1]:
import torch

In [9]:
def describe(x):
    print(f"Type: ",x.type())
    print(f"Shape/Size: ", x.shape)
    print(f"Values: \n", x )

What is Tensor? 
Ans: A tensor is a multi-dimensional array/ data structure used in machine learning and deep learning to store data. It's a generalization of scalars (0D), vectors (1D tensor), and matrices (2D tensor) to higher dimensions.

In [ ]:
describe(torch.Tensor(2, 3)) #two rows three columns

Type:  torch.FloatTensor
Shape/Size:  torch.Size([2, 3])
Values: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
describe(torch.rand(2,3)) #uniform random

Type:  torch.FloatTensor
Shape/Size:  torch.Size([2, 3])
Values: 
 tensor([[0.9761, 0.5000, 0.6215],
        [0.3406, 0.1647, 0.4820]])


In [12]:
describe(torch.randn(2,3)) #random normal

Type:  torch.FloatTensor
Shape/Size:  torch.Size([2, 3])
Values: 
 tensor([[-3.0781, -0.6609,  0.2185],
        [-0.2627, -0.5420, -0.0502]])


In PyTorch, when a method has a _ (underscore) at the end, like add_() or relu_(), it means:
✅ The tensor will be changed directly — it will not create a new one. It is also known as in place. 

In [ ]:
x = torch.tensor([1.0, 2.0])
y = x.add(1)  # This makes a new tensor
print(x) 
print(y) 

tensor([1., 2.])
tensor([2., 3.])


In [16]:
x = torch.tensor([1.0, 2.0])
y = x.add_(1)  # This makes a new tensor
print("before add", x) 
print("after add", y) 

before add tensor([2., 3.])
after add tensor([2., 3.])
